# -*- coding: utf-8 -*-
"""1. Assignment- Pandas_Session_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1au-Lf95U5gIOe1d9KVPbnwb6SA-g4j2Q

## Assignment -  1

###  Import the necessary libraries
"""

import numpy as np
import pandas as pd

"""###  Import the dataset from this(https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user). <br>
Use sep= "|" while reading the data
"""

url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user'
users=pd.read_csv(url,sep='|')

"""### Assign it to a variable called users and use the 'user_id' as index"""

users=users.set_index('user_id')

"""### See the first 10 and last 10 entries """

users.head(10)

users.tail(10)

"""### What is the number of observations in the dataset?"""

print('No of observations: ',len(users))

"""### What is the number of columns in the dataset?"""

print('No of columns: ',len(users.columns))

"""### Print the name of all the columns."""

print(users.columns)

"""### How is the dataset indexed?"""

users.index

"""### What is the data type of each column?"""

users.dtypes

"""### Print only the occupation column"""

users['occupation']

"""### How many different occupations are in this dataset?"""

len(users['occupation'].unique())

"""### What is the most frequent occupation?"""

users['occupation'].max()

"""###  DataFrame Info."""

users.info(show_counts=True)

"""### Describe all the columns"""

users.describe(include='all')

"""### Summarize only the occupation column"""

users.groupby('occupation')['occupation'].count().sort_values(ascending=False)

"""###  What is the mean age of users?"""

users['age'].mean()

"""###  What is the age with least occurrence?"""

users['age'].min()